version: "3"
services:
  webscrape:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=8000"
      - "traefik.http.routers.frontend.tls=false"
    volumes:
      - "$PWD/dist:/project/dist"
      - "$PWD/api/backend:/project/api/backend"
    ports:
      - "8000:8000"
