[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.docker]

[certificatesResolvers]
  [certificatesResolvers.myresolver]
    [certificatesResolvers.myresolver.acme]
      email = "your-email@example.com"
      storage = "acme.json"
      [certificatesResolvers.myresolver.acme.httpChallenge]
        entryPoint = "web"

[[tls.certificates]]
  certFile = "/etc/traefik/certs/ssl-cert.pem"
  keyFile = "/etc/traefik/certs/ssl-cert.key"
